#+TITLE: pile

[[https://img.shields.io/github/workflow/status/lepisma/pile/test.svg?style=flat-square]] [[https://img.shields.io/github/v/tag/lepisma/pile.svg?style=flat-square]]

Source code for my [[https://lepisma.xyz/][web site]] setup. ~pile~ wraps around ~org-publish~ and adds a few
functions to improve the experience of generating static htmls.

The package lives on a /commit-on-need/ basis so might not be in good shape at any
point in time. The basic item here is a ~pile-project~ which can be of the /wiki/
type (focused on having updatable set of pages, like in a regular wiki) or a
/blog/ type (a stream of posts, dated and tagged). These projects then define the
kind of embellishments the pages get using a bunch of hooks and/or org level
config using the ~org-export~ and ~org-publish~ infrastructure.

Overall this setup is sometimes annoying and slow but works mostly okay for me.

* Workflow Notes
** Hooks
There are two hooks that work with the ~pile-publish-~ functions. See
~./pile-hook.el~ for example functions.

1. ~pile-pre-publish-hook~. Functions here run in the to-be-published Org mode
   buffer and don't take any argument.
2. ~pile-post-publish-hook~. These take input (Org) file path and output file path
   (HTML).
